name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    name: Build - DuckDB ${{ matrix.duckdb_version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        duckdb_version:
          - "1.1.2"
          - "1.1.3"
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: "0.13.0"
      - uses: astral-sh/setup-uv@v5
      - run: zig build -Dduckdb-version=${{ matrix.duckdb_version }} -Dinstall-headers --verbose --summary new
      - run: zig build test -Dduckdb-version=${{ matrix.duckdb_version }} -Dplatform=linux_amd64_gcc4 --summary none
